# Generated by Django 6.0 on 2025-12-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام دانشکده')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد دانشکده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام دانشگاه')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد دانشگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام گروه آموزشی')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد گروه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.faculty', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه\u200cهای آموزشی',
                'ordering': ['faculty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('weight', models.FloatField(default=1.0, verbose_name='ضریب')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_weights', to='admissions.admissionround', verbose_name='فراخوان')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.university', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'ضریب دانشگاه',
                'verbose_name_plural': 'ضرایب دانشگاه\u200cها',
                'unique_together': {('university', 'round')},
            },
        ),
    ]
