# Generated by Django 6.0 on 2025-12-06 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(help_text='مثال: ma-conditions, phd-how-to-register', unique=True, verbose_name='شناسه URL')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن اطلاعیه')),
                ('priority', models.CharField(choices=[('LOW', 'عادی'), ('MEDIUM', 'متوسط'), ('HIGH', 'مهم'), ('URGENT', 'فوری')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('for_university_admins', models.BooleanField(default=True, verbose_name='مسئولین دانشگاه')),
                ('for_faculty_admins', models.BooleanField(default=True, verbose_name='مسئولین دانشکده')),
                ('for_ma_talent', models.BooleanField(default=True, verbose_name='استعداد ارشد')),
                ('for_phd_talent', models.BooleanField(default=True, verbose_name='استعداد دکتری')),
                ('for_phd_exam', models.BooleanField(default=True, verbose_name='آزمون دکتری')),
                ('for_olympiad', models.BooleanField(default=True, verbose_name='المپیاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'اطلاعیه ادمین',
                'verbose_name_plural': 'اطلاعیه\u200cهای ادمین',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(blank=True, help_text='کد یکتا برای شناسایی اطلاعیه', max_length=20, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان مطلب')),
                ('body', models.TextField(verbose_name='متن کامل')),
                ('category', models.CharField(choices=[('GENERAL', 'عمومی'), ('MA_TALENT', 'استعداد درخشان ارشد'), ('PHD_TALENT', 'استعداد درخشان دکتری'), ('PHD_EXAM', 'آزمون دکتری'), ('OLYMPIAD', 'المپیاد علمی')], max_length=20, verbose_name='گروه مطلب')),
                ('priority', models.IntegerField(default=0, help_text='عدد بزرگتر = اولویت بیشتر در نمایش', verbose_name='ترتیب')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/%Y/%m/', verbose_name='پیوست')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-priority', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-priority', '-published_at'], name='content_ann_priorit_efdc0e_idx'), models.Index(fields=['category', 'is_published'], name='content_ann_categor_b6e5cb_idx')],
            },
        ),
    ]
