# Generated by Django 6.0 on 2025-12-06 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('step_type', models.CharField(choices=[('APPLICANT_SUBMITTED', 'ارسال توسط داوطلب'), ('INITIAL_CHECK', 'بررسی اولیه'), ('ELIGIBLE', 'واجد شرایط'), ('FACULTY_REVIEW', 'بررسی دانشکده'), ('FINAL_REVIEW', 'بررسی نهایی'), ('RETURNED', 'برگشت داده شده'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('OTHER', 'سایر')], max_length=30, verbose_name='نوع مرحله')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='applications.application', verbose_name='درخواست')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'لاگ گردش کار',
                'verbose_name_plural': 'لاگ\u200cهای گردش کار',
                'ordering': ['application', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('document_type', models.CharField(choices=[('IDENTITY_DOCS', 'مدارک شناسایی'), ('EDUCATION_DOCS', 'مدارک تحصیلی')], max_length=30, verbose_name='نوع مدارک')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('APPROVED_WITH_DEFECT', 'تاییدشده با نقص'), ('REJECTED', 'فرم تایید نشده')], default='PENDING', max_length=30, verbose_name='وضعیت بررسی')),
                ('comment', models.TextField(blank=True, verbose_name='نظر بررسی\u200cکننده')),
                ('defects', models.JSONField(blank=True, default=dict, help_text='مثال: {"personal_photo": true, "national_card": false}', verbose_name='موارد نقص')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_reviews', to='applications.application', verbose_name='درخواست')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'بررسی مدارک',
                'verbose_name_plural': 'بررسی\u200cهای مدارک',
                'ordering': ['application', 'document_type', '-created_at'],
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
