# Generated by Django 6.0 on 2025-12-06 03:47

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ma_talent_access', models.BooleanField(default=False, verbose_name='دسترسی به استعداد درخشان ارشد')),
                ('has_phd_talent_access', models.BooleanField(default=False, verbose_name='دسترسی به استعداد درخشان دکتری')),
                ('has_phd_exam_access', models.BooleanField(default=False, verbose_name='دسترسی به آزمون دکتری')),
                ('has_olympiad_access', models.BooleanField(default=False, verbose_name='دسترسی به المپیاد علمی')),
                ('has_full_access', models.BooleanField(default=False, verbose_name='دسترسی کامل به همه موارد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسترسی ادمین',
                'verbose_name_plural': 'دسترسی\u200cهای ادمین',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='نشانی محل سکونت دائم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل داوطلب',
                'verbose_name_plural': 'پروفایل\u200cهای داوطلبان',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('national_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('role', models.CharField(choices=[('APPLICANT', 'داوطلب'), ('UNIVERSITY_ADMIN', 'مسئول دانشگاه'), ('FACULTY_ADMIN', 'مسئول دانشکده'), ('SUPERADMIN', 'سوپر ادمین')], default='APPLICANT', max_length=20, verbose_name='نقش')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('birth_certificate_serial', models.CharField(blank=True, max_length=30, verbose_name='شماره سریال شناسنامه')),
                ('birth_certificate_issue_place', models.CharField(blank=True, max_length=100, verbose_name='محل صدور شناسنامه')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تولد')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='محل تولد')),
                ('military_status', models.CharField(blank=True, choices=[('EXEMPT', 'معافیت دائم'), ('EDUCATIONAL_EXEMPT', 'معافیت تحصیلی'), ('SERVING', 'در حال خدمت'), ('COMPLETED', 'پایان خدمت'), ('MEDICAL_EXEMPT', 'معافیت پزشکی'), ('INCLUDED', 'مشمول')], help_text='فقط برای مردان الزامی است', max_length=30, verbose_name='وضعیت نظام وظیفه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
