# Generated by Django 6.0 on 2025-12-06 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermission',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='core.faculty', verbose_name='دانشکده\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='adminpermission',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['UNIVERSITY_ADMIN', 'FACULTY_ADMIN', 'SUPERADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ادمین'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
