# Generated by Django 5.0 on 2025-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exam_rank',
            field=models.PositiveIntegerField(blank=True, help_text='رتبه کسب شده در آزمون دکتری (فقط برای مسیر PHD_EXAM)', null=True, verbose_name='رتبه آزمون دکتری'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'ثبت\u200cنام اولیه'), ('PROGRAM_SELECTED', 'رشته انتخاب شد'), ('PERSONAL_INFO_COMPLETED', 'اطلاعات شخصی تکمیل شد'), ('IDENTITY_DOCS_UPLOADED', 'مدارک شناسایی آپلود شد'), ('EDU_INFO_COMPLETED', 'اطلاعات تحصیلی تکمیل شد'), ('EDU_DOCS_UPLOADED', 'مدارک تحصیلی آپلود شد'), ('SUBMITTED', 'ارسال شده (منتظر بررسی)'), ('UNDER_UNIVERSITY_REVIEW', 'در حال بررسی توسط مسئول دانشگاه'), ('APPROVED_BY_UNIVERSITY', 'تایید شده توسط مسئول دانشگاه'), ('REJECTED_BY_UNIVERSITY', 'رد شده توسط مسئول دانشگاه'), ('RETURNED_FOR_CORRECTION', 'برگشت برای اصلاح نواقص'), ('UNDER_FACULTY_REVIEW', 'در حال بررسی توسط مسئول دانشکده'), ('FACULTY_REVIEW_COMPLETED', 'بررسی دانشکده تکمیل شد'), ('COMPLETED', 'تکمیل شده'), ('INELIGIBLE', 'فاقد شرایط'), ('DELETED', 'حذف شده')], db_index=True, default='NEW', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='application',
            name='university_review_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('APPROVED_WITH_DEFECT', 'تایید با نقص'), ('REJECTED', 'رد شده')], db_index=True, default='PENDING', max_length=30, verbose_name='وضعیت بررسی مسئول دانشگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationchoice',
            unique_together={('application', 'priority'), ('application', 'program')},
        ),
    ]
