# Generated by Django 6.0 on 2025-12-06 03:47

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('type', models.CharField(choices=[('PERSONAL_PHOTO', 'عکس پرسنلی'), ('NATIONAL_CARD', 'کارت ملی'), ('ID_CARD', 'شناسنامه'), ('BSC_CERT', 'مدرک کارشناسی'), ('BSC_TRANSCRIPT', 'ریزنمرات کارشناسی'), ('MSC_CERT', 'مدرک کارشناسی ارشد'), ('MSC_TRANSCRIPT', 'ریزنمرات کارشناسی ارشد'), ('MSC_EXCELLENCE_CERT', 'فرم رتبه ممتاز ارشد'), ('EXCELLENCE_CERT', 'گواهی دانشجوی ممتاز'), ('GRADUATION_CERT', 'گواهی فارغ\u200cالتحصیلی'), ('ENROLLMENT_CERT', 'گواهی اشتغال به تحصیل'), ('OLYMPIAD_CERT', 'فرم کسب رتبه در المپیاد علمی'), ('ENGLISH_TEST_CERT', 'فرم کسب امتیاز از آزمون\u200cهای زبان انگلیسی'), ('OTHER', 'سایر')], max_length=30, verbose_name='نوع مدرک')),
                ('file', models.FileField(upload_to=apps.documents.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='فایل')),
                ('status', models.CharField(choices=[('UPLOADED', 'آپلود شده'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='UPLOADED', max_length=20, verbose_name='وضعیت')),
                ('review_comment', models.TextField(blank=True, verbose_name='نظر بررسی\u200cکننده')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='درخواست')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
                'ordering': ['application', 'type', '-uploaded_at'],
            },
        ),
    ]
