# Generated by Django 6.0 on 2025-12-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('degree_level', models.CharField(choices=[('MA', 'کارشناسی ارشد'), ('PHD', 'دکتری')], max_length=10, verbose_name='مقطع تحصیلی')),
                ('code', models.CharField(max_length=20, verbose_name='کد رشته')),
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('orientation', models.CharField(blank=True, max_length=255, verbose_name='گرایش')),
                ('bachelor_related_field', models.CharField(blank=True, max_length=255, verbose_name='رشته مرتبط کارشناسی')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برنامه تحصیلی',
                'verbose_name_plural': 'برنامه\u200cهای تحصیلی',
                'ordering': ['round', 'faculty', 'department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فراخوان')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('type', models.CharField(choices=[('MA_TALENT', 'استعداد درخشان کارشناسی ارشد'), ('PHD_TALENT', 'استعداد درخشان دکتری'), ('PHD_EXAM', 'آزمون دکتری'), ('OLYMPIAD', 'المپیاد علمی')], max_length=20, verbose_name='نوع فراخوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('registration_start', models.DateTimeField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateTimeField(verbose_name='پایان ثبت\u200cنام')),
                ('documents_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت ارسال مدارک')),
                ('result_publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اعلام نتایج')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'فراخوان پذیرش',
                'verbose_name_plural': 'فراخوان\u200cهای پذیرش',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('year', 'type')},
            },
        ),
    ]
