# Generated by Django 6.0 on 2025-12-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.department', verbose_name='گروه آموزشی'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.faculty', verbose_name='دانشکده'),
        ),
        migrations.AddField(
            model_name='program',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admissions.admissionround', verbose_name='فراخوان'),
        ),
    ]
